# Document:
# http://simiki.org/docs/configuration.html

url: 
title: 
keywords: 
description: Kafka Wiki 
author: 
deploy:
  - type: git
    remote: 'https://github.com/kafka-learn/kafka-summary'
    branch: 'gh-pages'
